# Generated by Django 5.1.4 on 2024-12-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='birds_images/')),
                ('sound', models.FileField(blank=True, null=True, upload_to='bird_sounds/')),
                ('wiki_link', models.URLField()),
            ],
        ),
    ]
